global:
  # How frequently to scrape targets by default.
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'cloudbase'
    metrics_path: /actuator/prometheus
    eureka_sd_configs:
      - server: http://192.168.0.105:8011/eureka
  - job_name: 'cloudbase-config'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['192.168.0.105:8010']
  - job_name: 'cloudbase-eureka'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['192.168.0.105:8011']
