apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}-deploy
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.internalPort }}
