carinfo:
  kafka:
    producer:
      topic: scrape-events
    consumer:
      topic: car-info-events

server:
  port: 8092


spring:
  application:
    name: car-info-service
  config:
    import: optional:configserver:http://localhost:8010
  profiles:
    active: dev
  kafka:
    producer:
      bootstrap-servers: localhost:29092,localhost:29093,localhost:29094
    consumer:
      bootstrap-servers: localhost:29092,localhost:29093,localhost:29094
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: car-info-events-group1
    admin:
      properties:
        bootstrap.servers: localhost:29092,localhost:29093,localhost:29094
  data:
    mongodb:
#      uri: mongodb://localhost:27017
      uri: mongodb+srv://microservices:<password>@cluster0.t6wct.mongodb.net/?retryWrites=true&w=majority
      database: grep-car-info
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8011/eureka
  instance:
    prefer-ip-address: true
    instance-id: car-info-service-${spring.cloud.client.ip-address}:${server.port}
