{{- define "common.deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.applicationName }}-deploy
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image }}"
        imagePullPolicy: IfNotPresent
        {{- if .Values.kafka1Env_enabled }}
        {{- include "deploy.env.kafka1" . | default "" | indent 8 }}
        {{- end }}
        {{- if .Values.zookeeperEnv_enabled }}
        {{- include "deploy.env.zookeeper" . | default "" | indent 8 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
{{- end }}