{{- define "common.service" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}-{{ .Values.global.activeProfile }}-service
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.applicationName }}-{{ .Values.global.activeProfile }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name | default "web" | quote }}
 {{- end }}
