spring:
  application:
    name: car-eureka
  config:
    import: optional:configserver:http://localhost:8010
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
app:
  instance:
    host: localhost
eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://${app.instance.host}:${server.port}/eureka
    register-with-eureka: false
  instance:
    prefer-ip-address: true
server:
  port: 8011

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
