apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'cloudcar'
        metrics_path: /actuator/prometheus
        eureka_sd_configs:
          - server: "http://{{ .Values.target.eurekaHost }}/eureka"
      - job_name: 'cloudcar-config'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['{{ .Values.target.configServerHost }}']
      - job_name: 'cloudcar-eureka'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['{{ .Values.target.eurekaHost }}']
