apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}-service
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.applicationName }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name | default "web" | quote }}
