scrap:
  shoushi:
    url: fillFromConfigServer
spring:
  application:
    name: car-scrap
  config:
    import: optional:configserver:http://localhost:8010
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8011/eureka
  instance:
    prefer-ip-address: true
    instance-id: car-scrap-${random.value}
